version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    restart: always
    hostname: https://protogen-armms.rayenmanai.site
    networks:
      - armms-network
    container_name: protogen-fe-app

networks:
  armms-network:
    driver: bridge
