name: Deploy ProtoGen-fe

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Kill Container if exists
        run: |
          if [ "$(docker ps -q -f name=protogen-fe-app)" ]; then
            docker kill protogen-fe-app
          fi

      - name: Remove Container if exists
        run: |
          if [ "$(docker ps -aq -f name=protogen-fe-app)" ]; then
            docker rm protogen-fe-app
          fi

      - name: Build and Deploy Container
        run: |
          docker compose down || true
          docker compose up --build -d
